"""
STEP 7: Model Deployment using Streamlit
------------------------------------------
SafeFall AI - Elderly Fall Detection Monitoring Dashboard
CareVision HealthTech Pvt. Ltd.

Run locally:
    streamlit run app.py

Deploy on Streamlit Cloud:
    1. Push this whole folder (including the model/scaler/label files
       generated by 2_train_model.py) to a GitHub repo.
    2. Go to https://share.streamlit.io , connect the repo, set
       app.py as the entry point, and deploy.
"""

import os
import tempfile
import urllib.request

import cv2
import numpy as np
import pandas as pd
import streamlit as st
import mediapipe as mp
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision as mp_vision
from tensorflow.keras.models import load_model
import joblib

# ----------------------------------------------------------------------
# PAGE CONFIG
# ----------------------------------------------------------------------
st.set_page_config(
    page_title="SafeFall AI - Elderly Fall Detection",
    page_icon="🚨",
    layout="wide",
)

MODEL_PATH = "fall_detection_model.h5"
SCALER_PATH = "feature_scaler.pkl"
LABELS_PATH = "label_encoder_classes.npy"
POSE_MODEL_PATH = "pose_landmarker.task"
POSE_MODEL_URL = (
    "https://storage.googleapis.com/mediapipe-models/pose_landmarker/"
    "pose_landmarker_lite/float16/1/pose_landmarker_lite.task"
)
FALL_LABEL = "fall"
ALERT_CONFIDENCE_THRESHOLD = 0.60
VIDEO_FRAME_SAMPLE_RATE = 5  # process every Nth frame for speed

# Hardcoded BlazePose 33-point skeleton connections. NOTE: we define this
# manually instead of importing mp.solutions.pose.POSE_CONNECTIONS because
# the legacy mp.solutions API has been breaking with
# "AttributeError: module 'mediapipe' has no attribute 'solutions'" on
# recent MediaPipe releases. This list is identical to the official one,
# just declared directly so we don't depend on the broken module.
POSE_CONNECTIONS = [
    (0, 1), (1, 2), (2, 3), (3, 7), (0, 4), (4, 5), (5, 6), (6, 8),
    (9, 10),
    (11, 12), (11, 13), (13, 15), (15, 17), (15, 19), (15, 21), (17, 19),
    (12, 14), (14, 16), (16, 18), (16, 20), (16, 22), (18, 20),
    (11, 23), (12, 24), (23, 24),
    (23, 25), (25, 27), (27, 29), (29, 31), (27, 31),
    (24, 26), (26, 28), (28, 30), (30, 32), (28, 32),
]


# ----------------------------------------------------------------------
# CACHED LOADERS
# ----------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    model = load_model(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
    class_names = np.load(LABELS_PATH, allow_pickle=True)
    return model, scaler, class_names


@st.cache_resource
def get_pose_detector():
    # Download the pose model file on first run if it isn't already in
    # the repo (Streamlit Cloud gets a fresh filesystem each deploy).
    if not os.path.isfile(POSE_MODEL_PATH):
        urllib.request.urlretrieve(POSE_MODEL_URL, POSE_MODEL_PATH)

    base_options = mp_python.BaseOptions(model_asset_path=POSE_MODEL_PATH)
    options = mp_vision.PoseLandmarkerOptions(
        base_options=base_options,
        running_mode=mp_vision.RunningMode.IMAGE,
    )
    return mp_vision.PoseLandmarker.create_from_options(options)


# ----------------------------------------------------------------------
# SESSION STATE (dashboard counters persist across uploads)
# ----------------------------------------------------------------------
if "total_detected" not in st.session_state:
    st.session_state.total_detected = 0
if "fall_count" not in st.session_state:
    st.session_state.fall_count = 0
if "normal_count" not in st.session_state:
    st.session_state.normal_count = 0
if "activity_log" not in st.session_state:
    st.session_state.activity_log = []  # list of dicts: {activity, confidence}


# ----------------------------------------------------------------------
# CORE PREDICTION FUNCTION
# ----------------------------------------------------------------------
def draw_pose_landmarks(image_bgr, landmarks):
    """
    Manually draws the pose skeleton with OpenCV instead of
    mp.solutions.drawing_utils (avoids the broken legacy API).
    """
    h, w = image_bgr.shape[:2]
    points = [(int(lm.x * w), int(lm.y * h)) for lm in landmarks]

    for start_idx, end_idx in POSE_CONNECTIONS:
        cv2.line(image_bgr, points[start_idx], points[end_idx], (0, 255, 0), 2)
    for x, y in points:
        cv2.circle(image_bgr, (x, y), 4, (0, 0, 255), -1)

    return image_bgr


def predict_frame(frame_bgr, model, scaler, class_names, pose_detector):
    """
    Runs pose detection + classification on a single BGR frame.
    Returns (annotated_frame, predicted_label, confidence) or
    (annotated_frame, None, None) if no pose was detected.
    """
    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame_rgb)
    result = pose_detector.detect(mp_image)

    annotated = frame_bgr.copy()

    if not result.pose_landmarks:
        return annotated, None, None

    landmarks = result.pose_landmarks[0]  # first detected person
    annotated = draw_pose_landmarks(annotated, landmarks)

    row = []
    for lm in landmarks:
        visibility = getattr(lm, "visibility", 0.0)
        row.extend([lm.x, lm.y, lm.z, visibility])

    features = np.array(row, dtype="float32").reshape(1, -1)
    features_scaled = scaler.transform(features)
    features_reshaped = features_scaled.reshape(1, features_scaled.shape[1], 1)

    probs = model.predict(features_reshaped, verbose=0)[0]
    pred_idx = int(np.argmax(probs))
    confidence = float(probs[pred_idx])
    label = str(class_names[pred_idx])

    return annotated, label, confidence


def log_prediction(label, confidence):
    st.session_state.total_detected += 1
    if label.lower() == FALL_LABEL:
        st.session_state.fall_count += 1
    else:
        st.session_state.normal_count += 1
    st.session_state.activity_log.append({"activity": label, "confidence": round(confidence, 3)})


def show_alert_if_fall(label, confidence):
    if label.lower() == FALL_LABEL and confidence >= ALERT_CONFIDENCE_THRESHOLD:
        st.error(f"🚨 EMERGENCY ALERT: Fall Detected! (confidence: {confidence:.2%}) "
                  f"Caregiver notification triggered.")
    elif label.lower() == FALL_LABEL:
        st.warning(f"⚠️ Possible fall detected but confidence is low ({confidence:.2%}). "
                    f"Please verify manually.")


# ----------------------------------------------------------------------
# SIDEBAR
# ----------------------------------------------------------------------
st.sidebar.title("🚨 SafeFall AI")
st.sidebar.caption("CareVision HealthTech Pvt. Ltd.")
st.sidebar.markdown("---")
mode = st.sidebar.radio("Select input type", ["Upload Image", "Upload Video"])
st.sidebar.markdown("---")
if st.sidebar.button("Reset Dashboard Counters"):
    st.session_state.total_detected = 0
    st.session_state.fall_count = 0
    st.session_state.normal_count = 0
    st.session_state.activity_log = []
    st.rerun()

# ----------------------------------------------------------------------
# MAIN HEADER
# ----------------------------------------------------------------------
st.title("SafeFall AI - Elderly Fall Detection Monitoring")
st.markdown(
    "Computer vision powered activity monitoring for elderly safety. "
    "Upload a snapshot or video clip to classify activity and detect falls."
)

try:
    model, scaler, class_names = load_artifacts()
    pose_detector = get_pose_detector()
except Exception as e:
    st.error(
        "Could not load model artifacts. Make sure fall_detection_model.h5, "
        "feature_scaler.pkl, and label_encoder_classes.npy are in the repo "
        f"root alongside app.py.\n\nError: {e}"
    )
    st.stop()

col_main, col_dashboard = st.columns([2, 1])

# ----------------------------------------------------------------------
# LEFT COLUMN: upload + prediction
# ----------------------------------------------------------------------
with col_main:
    if mode == "Upload Image":
        uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])
        if uploaded_file is not None:
            file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
            frame = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

            annotated, label, confidence = predict_frame(frame, model, scaler, class_names, pose_detector)

            st.image(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB),
                      caption="Pose Detection Output", use_container_width=True)

            if label is None:
                st.warning("No human pose detected in this image. Try another frame.")
            else:
                st.success(f"Predicted Activity: **{label.upper()}**  |  Confidence: **{confidence:.2%}**")
                show_alert_if_fall(label, confidence)
                log_prediction(label, confidence)

    else:  # Upload Video
        uploaded_video = st.file_uploader("Upload a video", type=["mp4", "avi", "mov"])
        if uploaded_video is not None:
            tfile = tempfile.NamedTemporaryFile(delete=False, suffix=".mp4")
            tfile.write(uploaded_video.read())
            video_path = tfile.name

            cap = cv2.VideoCapture(video_path)
            frame_placeholder = st.empty()
            status_placeholder = st.empty()
            progress_bar = st.progress(0)

            total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) or 1
            frame_idx = 0

            while cap.isOpened():
                ret, frame = cap.read()
                if not ret:
                    break

                if frame_idx % VIDEO_FRAME_SAMPLE_RATE == 0:
                    annotated, label, confidence = predict_frame(
                        frame, model, scaler, class_names, pose_detector
                    )
                    frame_placeholder.image(
                        cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB),
                        caption=f"Frame {frame_idx}", use_container_width=True
                    )
                    if label is not None:
                        status_placeholder.info(f"Activity: **{label.upper()}** | Confidence: {confidence:.2%}")
                        show_alert_if_fall(label, confidence)
                        log_prediction(label, confidence)

                frame_idx += 1
                progress_bar.progress(min(frame_idx / total_frames, 1.0))

            cap.release()
            os.unlink(video_path)
            st.success("Video processing complete.")

# ----------------------------------------------------------------------
# RIGHT COLUMN: monitoring dashboard
# ----------------------------------------------------------------------
with col_dashboard:
    st.subheader("📊 Monitoring Analytics")
    m1, m2, m3 = st.columns(3)
    m1.metric("Total Detected", st.session_state.total_detected)
    m2.metric("Falls", st.session_state.fall_count)
    m3.metric("Normal", st.session_state.normal_count)

    if st.session_state.activity_log:
        log_df = pd.DataFrame(st.session_state.activity_log)
        st.markdown("**Activity Distribution**")
        st.bar_chart(log_df["activity"].value_counts())

        st.markdown("**Recent Predictions**")
        st.dataframe(log_df.tail(10), use_container_width=True)
    else:
        st.caption("No activity logged yet. Upload an image or video to begin monitoring.")

st.markdown("---")
st.caption(
    "SafeFall AI Prototype - FA-2 Deliverable | Pose Estimation: MediaPipe | "
    "Classifier: 1D-CNN on pose landmarks | Not for real clinical use."
)
